### ISSUE TITLE
Question about "example_cnn.py"

### ISSUE THREAD

**Issue by TatsukiSerizawa** [SimonBlanke/Hyperactive#1]
Thank you for making a nice tool.

I have question about "example_cnn.py".
There was the following part in the code.
```
Optimizer = ParticleSwarmOptimizer(
    search_config, n_iter=3, metric="mean_squared_error", verbosity=0
)
```
I want to use "accuracy_score" in metric, but it couldn't use because error.
```
ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets
```

This code is a MNIST classification task, why is MSE used?

**Comment by SimonBlanke** [comment]
@TatsukiSerizawa 
Thank you a lot for your feedback!

This error occurs because of an overlap of the accuracy score of sklearn and keras. 
I already worked out a solution, that separates the metrics of both packages. I will do some additional testing today after work and release the fix in v0.4.1.6 afterwards.

I used the mse just to demonstrate, that you can also use a loss function for a classification task.

**Comment by SimonBlanke** [comment]
@TatsukiSerizawa 
v0.4.1.6 is now up. Doing an update via: 'pip install --upgrade hyperactive' should do the trick.
The readme now contains the available metrics for machine learning and deep learning models.

I also prepared a notebook, in which all the working metrics are shown for different kinds of datasets:
https://github.com/SimonBlanke/Hyperactive/blob/master/notebooks/metrics.ipynb

Thanks again for your feedback! :-)

**Comment by TatsukiSerizawa** [comment]
@SimonBlanke 
v0.4.1.6 allowed me to use metric "accuracy" on my PC.
Thank you for the quick answer!
