### ISSUE TITLE
How to handle exceptions / pruned trials and calculating n_iter from search space?

### ISSUE THREAD

**Issue by cryptocoinserver** [SimonBlanke/Hyperactive#22]
Thank you for this awesome python library. I'm currently working on an implementation of it for the Jesse project. Its a crypto backtesting framework. I use hyperactive to optimize the parameters of the trading strategies. [https://github.com/jesse-ai/jesse/blob/hyperactive/jesse/modes/optimize_hyperactive_mode/__init__.py](https://github.com/jesse-ai/jesse/blob/hyperactive/jesse/modes/optimize_hyperactive_mode/__init__.py)

The score is calculated from a ratio that describes how good the strategy performs and a custom created rate, that punishes parameter sets, that lead to too few or many trades compared to a given optimum.  Right now I set the score of backtests with too few trades (so few that ratio doesn't mean anything) and backtests that threw exceptions (sometimes this happens when parameters don't work together) to a very small score (0.0001).
Is this the right way? Wouldn't this punish the whole parameter set although it might be only one parameter that is "bad"?

How to set the n_iter dynamically. The search space of a strategy optimization can vary from one parameter with only a handful of values to 20 parameters with thousands of values and way more possible combinations. My idea was to calculate the number of possible combinations in the search space and use this as a base to calculate a good n_iter value from it. Any ideas or tips on how to do it. This logic approach would be better than letting the user guess what's a good value. It did research a little bit, but it seems the n_iter is often chosen by gut feeling instead of logic. 

Thank you for your help.

**Comment by SimonBlanke** [comment]
Hello @cryptocoinserver,

very cool, that you are using Hyperactive for your own project. I am glad you like my work.

I believe, that I can answer both of your questions:

1. If parameters do not work you can return numpy.nan. This was recently implemented and is much cleaner than just returning a low score, because the optimization algorithm ignores nan for its calculation. As if it is not part of the search space.
2. You seem to be concerned that you do to many n_iter because you would waste time. Maybe because your objective function is computationally expensive? Hyperactive has a feature called "memory", which is a dictionary that stores already explored positions in the search space. If Hyperactive encounters known positions it just looks up the score in the memory-dictionary and uses this instead of reevaluating the objective function. This can be switched on or off with the "memory"-parameter in .add_search(). So at some point the iterations will speed up to ~10.000/sec, because Hyperactive knows the entire search space. But be aware, that the sequence-model-based optimizers have a long (computationally expensive) optimization step. So the iteration will take some time even though the evaluation is fast (T iter = T opt + T eval) . Other optimization algorithms are fine though.

I hope I was able to answer all of your questions. I will leave this issue open. If all of your questions have been answered you can close the issue yourself.

**Comment by cryptocoinserver** [comment]
Perfect. Thank you. I return np.nan now. 
I read about the memory it's on by default right?
About n_iter so what do you think would be a good calculation based on the possible combinations for it.
It should be far smaller right?
Thank you.

**Comment by SimonBlanke** [comment]
Yes, the memory is activated by default.

The n_iter is a difficult subject, because it really depends on the time (or computational resources) you want to spend. If the size of your entire search space is 1000 but doing 10 iterations takes 10 hours, how much iterations should you do? If your search space has 1000 positions and you do 1000 iterations but the best score seems too bad you should probably change the ranges of your search space dimensions.

So there is never a clear answer. It really depends on the time you are willing to spend.

My strategy is to do a quick optimization run that takes ~1 min. in the beginning. After that I might adjust the search space a bit and do additional runs.
If you do that you can [transfer the memory from one run to the next].(https://github.com/SimonBlanke/Hyperactive/blob/master/examples/optimization_applications/memory.py)

This is a difficult and subjective topic, but I hope I was able to help you with this.

**Comment by cryptocoinserver** [comment]
I see. Thank you a lot!
