### ISSUE TITLE
Particle Swarm Optimizer

### ISSUE THREAD

**Issue by stanfordkim** [SimonBlanke/Hyperactive#28]
In Particle Swarm Optimizer the parameters what we can set as following. But in PSO the number of particles is a very important parameter we need to consider. How to set the number of particles because we can't see the parameter value setting in the function.
optimizer = ParticleSwarmOptimizer(inertia=0.4, cognitive_weight=0.7, social_weight=0.7, temp_weight=0.3, rand_rest_p=0.05)

**Comment by SimonBlanke** [comment]
Hello @stanfordkim,

you can set the number of particles with the "population"-parameter. By default the population is 10. You didn't see this parameter because I failed to update the [optimization-tutorial](https://github.com/SimonBlanke/optimization-tutorial). I have now added this parameter to the tutorial.

Thank you for the question @stanfordkim! If you have any further questions or suggestions, just let me know.

**Comment by stanfordkim** [comment]
Hi  Simon Blanke:

Thank you for your reply.

Yours sincerely.
