### ISSUE TITLE
Memoize evaluation results across multiple processes

### ISSUE THREAD

**Issue by 0liu** [SimonBlanke/Hyperactive#32]
Hi Simon,

I'm not sure if this is an enhancement request or it's already done. With `memory = True` Hyperactive can memoize evaluation results for later use, while in multiprocessing setup with n_jobs > 1, it looks each process keeps its own local dictionary and they cannot access the results from other processes, because I save evaluation results of all processes and there are some identical parameter sets.

This feature would save more time and should not be very hard to implement, for example, using a global Manager().dict(), or [share a cache](https://newbedev.com/how-to-share-a-cache-between-multiple-processes). I'm now manually wrapping my objective function so it looks up a synchronized dict() before doing actual evaluation, but it would be much nicer to have Hyperactive manage it.
Thanks!

**Comment by SimonBlanke** [comment]
I managed to implement the shared memory dictionary for multiprocessing in 5439daf8caec12e8944e6ed4c55516c6200a8816. It requires >=0.3.3 of Gradient-Free-Optimizers (because I needed to enable the pass through of the shared memory dict). 
The shared memory dictionary is automatically activated if memory=True and is shared between all objective functions that are equal. There is no additional input required by the user. Compatibility with the memory_warm_start parameter is also ensured.

The shared memory is [tested](https://github.com/SimonBlanke/Hyperactive/blob/master/tests/test_memory/test_shared_memory.py) with multiple tests that confirm the speedup for n_jobs>1.

Offtopic @0liu: The early stopping also works for Hyperactive v3.3.0
