### ISSUE TITLE
TypeError: cannot pickle '_thread.RLock' object

### ISSUE THREAD

**Issue by frenzy1212** [SimonBlanke/Hyperactive#64]
I got this error in V4.4.0:   TypeError: cannot pickle '_thread.RLock' object
My code works fine in V4.3.0

**Comment by SimonBlanke** [comment]
Could you show a small example that I can run to reproduce this error?

**Comment by SimonBlanke** [comment]
I suspect the changes [in this commit](https://github.com/SimonBlanke/Hyperactive/commit/033642c0395dac6439f6c60078b732928254e378) to cause the error. However all tests passed for Python version 3.5 - 3.11 on ubuntu. Which os are you using?

**Comment by frenzy1212** [comment]
I'm using Python 3.8.10 on windows10.
The error occurs when using the multiprocessing,If 'njobs' set to 1,it works ok.

**Comment by frenzy1212** [comment]
I'm using Python 3.8.10 on windows10.
The error occurs when using the multiprocessing,If 'njobs' set to 1,it works ok.

**Comment by SimonBlanke** [comment]
Hello @frenzy1212,

unfortunately there seems to be a limitation as to which objects can be pickled in windows. Since I have no way to reproduce this error I can show you a workaround.

You can set the `distribution`-parameter to `"joblib"` in the `Hyperactive`-class. My joblib implementation does not include the setting of the lock of tqdm (because joblib does not have an initializer argument).

However you will probably experience the progress-bars jumping around in the command line when using multiple jobs (with joblib). This is what the tqdm-lock solves (for multiprocessing).
