### ISSUE TITLE
visualizations question

### ISSUE THREAD

**Issue by Enferlain** [SimonBlanke/Hyperactive#88]
Hey. This is not an issue, but I'd still like to ask, what was used to create the bayes gifs in docs/images? Like [this one](https://github.com/SimonBlanke/Hyperactive/blob/master/docs/images/bayes_convex_.gif)

**Comment by SimonBlanke** [comment]
Hello @Enferlain,

these kind of plots are generated by my own [plot-library](https://github.com/SimonBlanke/gradient-free-optimization-plots/tree/master/gradient_free_optimization_plots/search_path_gif). The API for this library has not matured though and is not made for users, yet.

Creating a search-path-gif currently only works with my optimization packages, because it accesses some non-public methods. If you have interest in using this package to create your own plots you could create an issue in the repository and explain what you are aiming for.
